[unstable]
# TODO: Find a way to replace compiler builtins with C implementation
build-std-features = ["compiler-builtins-mem"] # necessary due to iterators
build-std = ["core", "compiler_builtins"]

[build]
target = "x86_64-unknown-none"
